name: Check for crypto and Format

on:
  pull_request:

jobs:
  check:
    name: Check for crypto
    runs-on: ubuntu-latest
    if: github.repository_owner == 'defi-wonderland'

    steps:
      - uses: actions/checkout@v3

      - name: Check for crypto
        uses: defi-wonderland/check-crypto-action@v1
        with:
          title: Check private key and notify
          branch: dev
          notify_issue: false
          notify_check: true
          token: ${{ secrets.GITHUB_TOKEN }}

  format:
    name: Lint and Prettier
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.1'
          cache: 'pnpm'

      - name: Authenticate with GitHub Packages
        run: |
          echo "@defi-wonderland/privacy-pool-core-sdk:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc

      - name: Install project dependencies
        run: pnpm install --frozen-lockfile --prefer-frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Prettier
        run: pnpm prettier

      - name: Run Linter
        run: pnpm lint
